package com.example.t1mart.util

object AppConstant {
    const val LIST_PRODUCTS = "https://dummyjson.com/"
    const val NAME_CATEGORY = "category_passed"
    const val ID_CATEGORY = "id_category_passed"
    const val NAME_CATEGORY_1 = "smartphones"
    const val NAME_CATEGORY_2 = "laptops"
    const val NAME_CATEGORY_3 = "fragrances"
    const val NAME_CATEGORY_4 = "skincare"
    const val NAME_CATEGORY_5 = "groceries"
    const val NAME_CATEGORY_6 = "home-decoration"
    const val NAME_CATEGORY_7 = "furniture"
    const val NAME_CATEGORY_8 = "tops"
    const val NAME_CATEGORY_9 = "womens-dresses"
    const val NAME_CATEGORY_10 = "womens-shoes"
    const val NAME_CATEGORY_11 = "mens-shirts"
    const val NAME_CATEGORY_12 = "mens-shoes"
    const val NAME_CATEGORY_13 = "mens-watches"
    const val NAME_CATEGORY_14 = "womens-watches"
    const val NAME_CATEGORY_15 = "womens-bags"
    const val NAME_CATEGORY_16 = "womens-jewellery"
    const val NAME_CATEGORY_17 = "sunglasses"
    const val NAME_CATEGORY_18 = "automotive"
    const val NAME_CATEGORY_19 = "motorcycle"
    const val NAME_CATEGORY_20 = "lighting"

    const val TITLE_NAME_CATEGORY_1 = "Điện thoại"
    const val TITLE_NAME_CATEGORY_2 = "Laptop"
    const val TITLE_NAME_CATEGORY_3 = "Nước hoa"
    const val TITLE_NAME_CATEGORY_4 = "Chăm sóc da"
    const val TITLE_NAME_CATEGORY_5 = "Hàng hóa"
    const val TITLE_NAME_CATEGORY_6 = "Trang trí nhà cửa"
    const val TITLE_NAME_CATEGORY_7 = "Nội thất"
    const val TITLE_NAME_CATEGORY_8 = "Áo"
    const val TITLE_NAME_CATEGORY_9 = "Váy đầm"
    const val TITLE_NAME_CATEGORY_10 = "Giày nữ"
    const val TITLE_NAME_CATEGORY_11 = "Áo nam"
    const val TITLE_NAME_CATEGORY_12 = "Giày nam"
    const val TITLE_NAME_CATEGORY_13 = "Đồng hồ nam"
    const val TITLE_NAME_CATEGORY_14 = "Đồng hồ nữ"
    const val TITLE_NAME_CATEGORY_15 = "Túi xách nữ"
    const val TITLE_NAME_CATEGORY_16 = "Trang sức"
    const val TITLE_NAME_CATEGORY_17 = "Mắt kính"
    const val TITLE_NAME_CATEGORY_18 = "Đồ điện tử"
    const val TITLE_NAME_CATEGORY_19 = "Xe máy"
    const val TITLE_NAME_CATEGORY_20 = "Đèn điện"

    const val PROMOTION_1 = "Xả kho"
    const val PROMOTION_2 = "Đi chợ ngon"
    const val PROMOTION_3 = "Ưu đãi"
    const val PROMOTION_4 = "Mã giảm giá"
    const val PROMOTION_5 = "Tài chính"
    const val PROMOTION_6 = "Hàng giảm giá"
    const val PROMOTION_7 = "Mua sắm thả ga"

    const val TOP_1 = "Top bán chạy"
    const val TOP_2 = "Mua nhiều giảm sâu"
    const val TOP_3 = "Giao nhanh 2h"
    const val TOP_4 = "Mua 1 được 2"
    const val TOP_5 = "Chốt Deal Sale Hot"
    const val TOP_6 = "Top Deal tiêu dùng"
    const val TOP_7 = "Săn Deal HomeTech"

    const val SALE_1 = "Chuột phím sale đến 50%"
    const val SALE_2 = "Ưu đãi sách hot đến 50%"
    const val SALE_3 = "Mua Tivi giảm đến 50%"
    const val SALE_4 = "Thưởng thức Strongbow 4 vị"
    const val SALE_5 = "Giảm đến 50%"
    const val SALE_6 = "Bùng cháy triệu Deal"
}